CREATE TABLE ACCOUNTS
(
    ID VARCHAR(30) NOT NULL,
    ACCOUNTNUMBER VARCHAR(30) NOT NULL,
    BALANCE VARCHAR(30) NOT NULL,
    NAME VARCHAR(30) NOT NULL
);

CREATE TABLE USERS
(
    ID VARCHAR(20) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    AGE VARCHAR(30) NOT NULL
);


